server:
  type: simple
  applicationContextPath: /application
  adminContextPath: /admin
  connector:
    type: http
    port: 9090

#jerseyClient:
#  timeout: 500ms
#  connectionTimeout: 500ms
#  timeToLive: 1h
#  cookiesEnabled: false
#  maxConnections: 1024
#  maxConnectionsPerRoute: 1024
#  keepAlive: 0ms
#  retries: 0
#  userAgent: billy (test)
#  minThreads: 1
#  maxThreads: 128
#  workQueueSize: 8
#  gzipEnabled: true
#  gzipEnabledForRequests: true
#  chunkedEncodingEnabled: true
